export const FETCH_ALL_WOO_PRODUCTS = 'FETCH_ALL_WOO_PRODUCTS';
export const FETCH_SINGLE_PRODUCT = 'FETCH_SINGLE_PRODUCT';
export const SET_SINGLE_CATEGORY = 'SET_SINGLE_CATEGORY';
export const FETCH_PRODUCTS_FROM_SINGLE_CATEGORY =
  'FETCH_PRODUCTS_FROM_SINGLE_CATEGORY';
export const SINGLE_CATEGORY_FAILED = 'SINGLE_CATEGORY_FAILED';
export const PRODUCTS_ERRORS = 'PRODUCTS_ERRORS';
export const SINGLE_CATEGORY_PAGER_INCREASE = 'SINGLE_CATEGORY_PAGER_INCREASE';
export const UPDATE_SINGLE_CATEGORY_PAGE = 'UPDATE_SINGLE_CATEGORY_PAGE';
export const SINGLE_CATEGORY_PAGER_DECREASE = 'SINGLE_CATEGORY_PAGER_DECREASE';

export const ADD_PRODUCT_TO_FAVOURITES = 'ADD_PRODUCT_TO_FAVOURITES';
export const FILTER_FAVOURITES = 'FILTER_FAVOURITES';
export const DELETE_FAVOURITE = 'DELETE_FAVOURITE';
export const ADD_TO_DISABLED = 'ADD_TO_DISABLED';
export const FETCH_CATEGORY_BY_SLUG = 'FETCH_CATEGORY_BY_SLUG';
export const RESET_PAGE_COUNTER = 'RESET_PAGE_COUNTER';

export const ADD_PRODUCT_TO_CART = 'ADD_PRODUCT_TO_CART';
export const DELETE_FROM_CART_IF_PRODUCT_EXIST = 'DELETE_FROM_CART_IF_PRODUCT';
export const ADD_TO_DISABLED_IF_CLICKED = 'ADD_TO_DISABLED_IF_CLICKED';
export const DELETE_PRODUCT_FROM_BASKET = 'DELETE_PRODUCT_FROM_BASKET';
export const UPDATE_QUNTITY_INPUT = 'UPDATE_QUNTITY_INPUT';
export const UPDATE_QUANTITY_ON_CHANGE = 'UPDATE_QUANTITY_ON_CHANGE';
export const INCREMENT_QUANT = 'INCREMENT_QUANT';
export const DECREMENT_QUANT = 'DECREMENT_QUANT';
export const ENABLE_CONTACT_FORM = 'ENABLE_CONTACT_FORM';
export const DISABLE_CONTACT_FORM = 'DISABLE_CONTACT_FORM';

export const OPEN_CONFIRMATION_MODAL = 'OPEN_CONFIRMATION_MODAL';
export const CLOSE_CONFIRMATION_MODAL = 'CLOSE_CONFIRMATION_MODAL';

export const SAVE_SHIPPING_DETAILS = 'SAVE_SHIPPING_DETAILS';
export const RESET_SHIPPING_DETAILS = 'RESET_SHIPPING_DETAILS';

export const ADD_TO_SHOPPING_LIST = 'ADD_TO_SHOPPING_LIST';
export const DELETE_PURCHASED_PRODUCT_FROM_SHOPPING_LIST =
  'DELETE_PURCHASED_PRODUCT_FROM_SHOPPING_LIST';

export const OPEN_MODAL_MOVED_TO_SHOPPING_LIST =
  'OPEN_MODAL_MOVED_TO_SHOPPING_LIST';
export const CLOSE_MODAL_MOVED_TO_SHOPPING_LIST =
  'CLOSE_MODAL_MOVED_TO_SHOPPING_LIST';
export const SENDING_EMAIL_FAILED = 'SENDING_EMAIL_FAILED';
export const RESET_EMAIL_FAILED = 'RESET_EMAIL_FAILED';
export const ERROR_PAGE_ALERT = 'ERROR_PAGE_ALERT';
