export const OPEN_SEARCH_PANEL = 'OPEN_SEARCH_PANEL';
export const CLOSE_SEARCH_PANEL = 'CLOSE_SEARCH_PANEL';
export const INPUT_SEARCH_CHANGE = 'INPUT_SEARCH_CHANGE';
export const GET_PRODUCTS_ON_SEARCH_REQUEST = 'GET_PRODUCTS_ON_SEARCH_REQUEST';
export const FETCH_FOUND_PRODUCTS_PENDING = 'FETCH_FOUND_PRODUCTS_PENDING';
export const GET_PRODUCTS_ON_SEARCH_SUCCESS = 'GET_PRODUCTS_ON_SEARCH_SUCCESS';
export const CHANGE_LOCATION_AFTER_SEARCH = 'CHANGE_LOCATION_AFTER_SEARCH';
export const QUICK_SEARCH_INPUT_CHANGE = 'QUICK_SEARCH_INPUT_CHANGE';
export const GET_PRODUCTS_QUICK_SEARCH_REQUEST =
  'GET_PRODUCTS_QUICK_SEARCH_REQUEST';
export const GET_PRODUCTS_QUICK_SEARCH_SUCCESS =
  'GET_PRODUCTS_QUICK_SEARCH_SUCCESS';
export const RESET_SEARCH_RESULTS = 'RESET_SEARCH_RESULTS';
export const START_SEARCH_RESULTS = 'START_SEARCH_RESULTS';
export const FETCH_PRODUCTS_ON_LOAD_MORE = 'FETCH_PRODUCTS_ON_LOAD_MORE';
export const INCREASE_NUMBER_PAGES = 'INCREASE_NUMBER_PAGES';
export const UPDATE_NUMBER_PAGES = 'UPDATE_NUMBER_PAGES';
export const GET_PRODUCTS_QUICK_SEARCH_FAILED =
  'GET_PRODUCTS_QUICK_SEARCH_FAILED';
