export const routes = {
  HOME_PAGE: '/',
  GALLERY: '/gallery',
  PRODUCTS: '/all-products',
  LOGIN_URL: '/login',
  LOGOUT_URL: '/logout',
  MY_ACCOUNT: '/my-account',
  SAVED_ITEMS: '/saved-items',
  SHOPPING_LIST: '/shopping-list',
  CONTACT_US: '/contact',
  REGISTRATION: '/registration',
  ENGINE_BUILDING: '/engine-building-service',
  ROLL_CAGES: '/roll-cages',
  SINGLE_SEATER: '/single-seater-moulds',
  ALL_PRODUCTS: '/all-products',
  LATEST_NEWS: '/latest-news',
  PAGE_ERROR: '/page-error',
  EMAIL_ERROR: '/email-error',
};
