export const LOADING_TRUE = 'LOADING_TRUE';
export const LOGIN_IN_PROCESS = 'LOGIN_IN_PROCESS';
export const RENDER_ERRORS_SUBMISSION = 'RENDER_ERRORS_SUBMISSION';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_SIGNIN_FAIL = 'USER_SIGNIN_FAIL';
export const LOGOUT_USER_REQUEST = 'LOGOUT_USER_REQUEST';
export const LOGOUT_USER = 'LOGOUT_USER';

export const TOGGLE_PAGE_FADER = 'TOGGLE_PAGE_FADER';
export const CLOSE_PAGE_FADER = 'CLOSE_PAGE_FADER';
export const TOGGLE_BODY_FADE = 'TOGGLE_BODY_FADE';
export const CLOSE_BODY_FADE = 'CLOSE_BODY_FADE';
export const CLEAR_FAVOURITES = 'CLEAR_FAVOURITES';
