export const LOADING_USERS_IN_PROGRESS = 'LOADING_USERS_IN_PROGRESS';
export const GET_USERS_REQUEST = 'GET_USERS_REQUEST';
export const GET_CUSTOMERS_REQUEST = 'GET_CUSTOMERS_REQUEST';
export const GET_USERS_REQUEST_SUCCESS = 'GET_USERS_REQUEST_SUCCESS';
export const GET_CUSTOMER_DETAILS_REQUEST = 'GET_CUSTOMER_DETAILS_REQUEST';
export const GET_CUSTOMER_DETAILS = 'GET_CUSTOMER_DETAILS';
export const GET_USER_FAILED = 'GET_USER_FAILED';
