export const SHOW_ADD_TESTIMONIALS_BUTTON = "SHOW_ADD_TESTIMONIALS_BUTTON";

export const FETCH_USERS_REQUEST = "FETCH_USERS_REQUEST";
export const FETCH_USERS_REQUEST_SUCCESS = "FETCH_USERS_REQUEST_SUCCESS";
export const GET_USER_FAILED = "GET_USER_FAILED";

export const OPEN_TESTIMONIAL_FORM = "OPEN_TESTIMONIAL_FORM";
export const SHOW_LOGIN_ALERT_BUTTON = "SHOW_LOGIN_ALERT_BUTTON";
export const SHOW_ADD_TESTIMONIAL_FORM = "SHOW_ADD_TESTIMONIAL_FORM";
export const CLOSE_ADD_TESTIMONIAL_FORM = "CLOSE_ADD_TESTIMONIAL_FORM";
export const GET_USERNAME_DETAILS = "GET_USERNAME_DETAILS";

export const SHOW_SPINNER_WHEN_FETCHING_PROGRESS =
  "SHOW_SPINNER_WHEN_FETCHING_PROGRESS";

export const CLOSE_TESTIMONIALS_AFTER_SUBMISSION =
  "CLOSE_TESTIMONIALS_AFTER_SUBMISSION";
